### ISSUE TITLE
Addon installed but not visible

### ISSUE THREAD

**Issue by burtondev** [mrossini-ethz/vector-render#10]
I installed the addon and enabled it, however I don't see it in the Properties pane. Is it possible to share a screenshot of where I can find the enabled plugin in Blender?

I tried looking under Render Engine and I only see the default options.

I also looked in the navigation menu under Render and it was not there.

I am using Blender 2.91. Do I have to downgrade to Blender 2.8 for this addon to work?

**Comment by mbasaglia** [comment]
I'm having the same issue too

**Comment by mbasaglia** [comment]
I managed to get it to work: https://github.com/mrossini-ethz/vector-render/pull/11

**Comment by burtondev** [comment]
After logging this issue, I tested it out on an older version of Blender. That's when I realized it's only for rendering meshes and solids, not materials, etc.
It's not what I need for my work, but hopefully the fixes you made will be helpful to other users!

**Comment by anonimo82** [comment]
@mbasaglia you could be lucky with Freestyle-svg exporter.
It's included with Blender

**Comment by mbasaglia** [comment]
I fixed this addon to work anyway
