### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by anonimo82** [mrossini-ethz/vector-render#2]
Please, make lights affecting colors

**Comment by mrossini-ethz** [comment]
It might be possible to have flat shading like here: https://en.m.wikipedia.org/wiki/Shading#/media/File%3APhong-shading-sample.jpg . Would that be helpful? Casting shadows, however, would be extremely difficult.

**Comment by anonimo82** [comment]
Yes, something like that.
Do you agree with me?

**Comment by mrossini-ethz** [comment]
Yes, it would be good, I suppose. However, it would only work with sun lamps, point lights (maybe) but not with emissive surfaces (emission shader).

**Comment by anonimo82** [comment]
I guess this is ok, I never meant to propose emissive materials (but just because I don't use them).
And, this is a personal preference, but I'd support flat shading.

**Comment by mrossini-ethz** [comment]
Ok. I might find time to do it starting September. Or can you write some code?

**Comment by anonimo82** [comment]
No, I'm not a developer.

**Comment by anonimo82** [comment]
I'm not sure at all about this but, what if the light distance would affect (in a HSV colorspace) the darkness of a gradient?
The gradient itself being the light intensity

**Comment by mrossini-ethz** [comment]
I think we should forget about gradients. Imagine a rectangular polygon on the floor and two point lights above it. If you render it, you will see two bright spots on the polygon. This is effectively a very special gradient. You _can_ have gradients in SVG files, but only simple ones like linear and radial gradients (see [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients)). But there is no gradient with _two_ spots.

**Comment by anonimo82** [comment]
You're right.
I can't wait to see this.

**Comment by mrossini-ethz** [comment]
See what? Gradients?

**Comment by anonimo82** [comment]
No, the colour thing, eventually with shadows

**Comment by mrossini-ethz** [comment]
Check out the 'devel' branch and enable the setting 'Use lights'. For now, it only works with _sun_ lamps. Please give me some feedback.

**Comment by anonimo82** [comment]
I can't see any "use lights" option in the Vector Render options.

**Comment by anonimo82** [comment]
It works great!
It's almost perfect, just (please) add shadows too.

**Comment by mrossini-ethz** [comment]
Ensure that you are actually using the new development version (devel branch). Also, you must have 'draw faces' enabled.

**Comment by anonimo82** [comment]
Yes, I did.
It works, please, add shadows too.

**Comment by mrossini-ethz** [comment]
Adding shadows is _very_ difficult. This would take a great effort: developing it and then each time when calculating a scene.

**Comment by anonimo82** [comment]
No problem, thanks anyhow for making me an happy child ;)
Will you at least consider animations?

**Comment by mrossini-ethz** [comment]
SVG animations? That's certainly possible, but I would need a _lot_ of time.

**Comment by anonimo82** [comment]
If you do, you'll be my hero, really.
Just let me know either.

**Comment by mrossini-ethz** [comment]
Please do some testing with the current development version. I'm sure that there are some bugs.

**Comment by mrossini-ethz** [comment]
It would be relatively easy to add ambient light, specular light and a background (color).

**Comment by anonimo82** [comment]
Yes, it's not perfect.
In example, I created a scene with a plane and a box, the plane passes through the box, I can see some extra edges (edges that would be hidden by the plane)

**Comment by mrossini-ethz** [comment]
Yes, that is to be expected. Intersecting planes is _extremely_ difficult.

**Comment by anonimo82** [comment]
Partially lit faces are almost black

**Comment by mrossini-ethz** [comment]
Are you sure that they are actually lit? With sun lamps _everything_ facing away from the lamp is completely black. Render it using blender render (and flat shading) to compare.

Use two lamps maybe.

**Comment by anonimo82** [comment]
[render.zip](https://github.com/mrossini-ethz/vector-render/files/2343608/render.zip)
As in this example file, the box' face on the left is totally black, while the top face gets double the light.
Right face is well drawn.

**Comment by anonimo82** [comment]
Nevermind: I was using point lights, sun lights works as expected.

**Comment by anonimo82** [comment]
[Intersection.zip](https://github.com/mrossini-ethz/vector-render/files/2343615/Intersection.zip)
[Render.zip](https://github.com/mrossini-ethz/vector-render/files/2343611/Render.zip)

**Comment by mrossini-ethz** [comment]
Yes, point light should be ignored in the code. That's a bug.

**Comment by anonimo82** [comment]
Ok, but at some point I could need to use point or spot lights.

**Comment by anonimo82** [comment]
Any news?

**Comment by mrossini-ethz** [comment]
What do you expect me to do? I am expecting _you_ to be testing :-)

**Comment by anonimo82** [comment]
Yes, but what can I do more?
I guess I tested it enough, unless you suspect there's a bug to fix.

**Comment by anonimo82** [comment]
I tried to use all of the available primitives, but only polygon based primitives will render.
I'm attaching my .blend files for your reference.
[Blender.zip](https://github.com/mrossini-ethz/vector-render/files/2346355/Blender.zip)

**Comment by mrossini-ethz** [comment]
Great! I will then fix some small bugs that I have already identified and then merge it to master.

**Comment by anonimo82** [comment]
Great indeed. Any plan to support lights?

**Comment by mrossini-ethz** [comment]
Point lights? Yes.

**Comment by anonimo82** [comment]
Point and spot (at least)

**Comment by mrossini-ethz** [comment]
Spot doesn't work.

**Comment by anonimo82** [comment]
I know, in fact I asked you to support it

**Comment by mrossini-ethz** [comment]
I mean it's not possible. You can't have only part of a polygon lit.

**Comment by anonimo82** [comment]
I see, I tought about this too.
But a whole face can be the same color and subdividing could fake a partial lit face

**Comment by anonimo82** [comment]
Any update?

**Comment by anonimo82** [comment]
Please, will you add shadows to this?

**Comment by mrossini-ethz** [comment]
No. Casting shadows messes up everything. It would take forever to 'render'. And it's difficult to implement.

I merged the changes into master. Thanks for your help!
