### ISSUE TITLE
Alternative idea

### ISSUE THREAD

**Issue by anonimo82** [mrossini-ethz/vector-render#3]
Dear, don't reinvent the wheel.
There's the FreeStyle SVG Exporter (https://github.com/folkertdev/freestyle-svg-exporter) which does what Vector Render is supposed to, but with many advantages, such as:

- Support for rendering non tesselated geometry (NURBS Surfaces/Curves, Text and MetaBalls)
- Render animations

Unfortunately, FreeStyle SVG Exporter flaws in filling faces, as it messes up them.
So, the only additions that has to be made in it is:

- Make fills work as in Vector Render
- Make lights affects color lightness (whole faces - optional, because neither FreeStyle SVG Exporter supports this ATM)

I hope you'll merge your rendering algorithm with FreeStyle's

Thanks if you do.

**Comment by anonimo82** [comment]
Are you interested?

**Comment by anonimo82** [comment]
Please, let me know

**Comment by anonimo82** [comment]
Up

**Comment by mrossini-ethz** [comment]
I think the Plugins are too different.

**Comment by anonimo82** [comment]
Ok then, thanks for letting me know.
So, will you render animations?

**Comment by mrossini-ethz** [comment]
Maybe.

**Comment by anonimo82** [comment]
News?
