### ISSUE TITLE
Blender 2.8 compatibility

### ISSUE THREAD

**Issue by anonimo82** [mrossini-ethz/vector-render#4]
Please, make this AddOn compatible with Blender 2.8
On installing this I get an error about compatibility.

**Comment by anonimo82** [comment]
Nevermind, it was my fault. Suddenly the script works ok.

**Comment by anonimo82** [comment]
Uhm, no, it wasn't me. I saw the AddOn was listed and enabled and I thought it would have worked, but it's not the case.
So, some modifications are needed for 2.8 compatibility (and I don't know what)

Big thanks if you update.

**Comment by anonimo82** [comment]
P.S.: This is the error: 
`Traceback (most recent call last):
  File "C:\Users\Utente1\Downloads\Armory\2.80\scripts\modules\addon_utils.py", line 377, in enable
    raise Exception(f"Add-on '{module_name:s}' has not been upgraded to 2.8, ignoring")
Exception: Add-on 'vector-render' has not been upgraded to 2.8, ignoring
`

**Comment by anonimo82** [comment]
Any news?

**Comment by mrossini-ethz** [comment]
I have started experimenting with add-ons for 2.8

**Comment by anonimo82** [comment]
Any update here?

**Comment by mrossini-ethz** [comment]
Hi. My other plugin appears to work, although it is not finished. I think I could make this one work as well but I haven't started yet.

**Comment by anonimo82** [comment]
Great, let me know ASAP

**Comment by anonimo82** [comment]
Any update here?

**Comment by anonimo82** [comment]
Bump

**Comment by anonimo82** [comment]
Any news?

**Comment by anonimo82** [comment]
Hey...

**Comment by mrossini-ethz** [comment]
Try the new blender-2.8 branch. Note the following:
- "Apply modifiers" does not work.
- The color of the objects is the setting in "Materials" > "Viewport Display" > "Color".
- If you use lights, check the light intensity.

**Comment by anonimo82** [comment]
Thanks.
Did I say it already? You're my hero.

**Comment by anonimo82** [comment]
I'm having troubles installing the AddOn.
How should I do?

**Comment by mrossini-ethz** [comment]
Try downloading the ZIP file for the blender-2.8 branch. Then open blender and go to Edit, Preferences, then Add-ons. On the top right there is a button called "Install...". Click it and select the zipfile.

**Comment by anonimo82** [comment]
Yes, I did. But the render doesn't appear in the toolshelf.

**Comment by mrossini-ethz** [comment]
Did you find the add-on in the add-on list and clicked the checkbox?

**Comment by mrossini-ethz** [comment]
Oh, and btw the GUI is not in the render menu anymore. It's now in the scene menu.

**Comment by anonimo82** [comment]
Nevermind, I made it to install and use.
I have a problem with lights by the way, lit faces are white.

**Comment by mrossini-ethz** [comment]
Yes, see my comment above. Light intensity in Blender seems to bee 1000x greater by default in version 2.8. I'll try to figure it out.

**Comment by mrossini-ethz** [comment]
It's complicated. Just reduce the brightness of your lights by 1000 or something.

**Comment by anonimo82** [comment]
Yes, I saw your post. I tried with a 6W lamp, same results. And the default light is 1000W strong.

**Comment by anonimo82** [comment]
Any news?
