### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by anonimo82** [mrossini-ethz/vector-render#5]
Please, add export animations to this.

**Comment by mrossini-ethz** [comment]
I will try if I find the time.

**Comment by anonimo82** [comment]
Big thank you.
I hope you'll made it.

Il giorno sab 29 dic 2018, 17:43 Marco Rossini <notifications@github.com>
ha scritto:

**Comment by mrossini-ethz** [comment]
I made a test and it will work. However, SVG does not appear to be made for frame based animations. I had to use a workaround. I think long animations will be a problem.

I will put things together and hopefully tomorrow you'll get a first version.

**Comment by anonimo82** [comment]
There are 2 ways to animate SVGs:
1) Put each frame as a layer and flip layers
2) Code animations as SVG markup (this would be useful and suitable when moving/rotating/scaling objects in 2D only and, eventually, along a path)

AFAIK, the 1st is the most used, but the 2nd is more suitable.
If you find a way to prevent rotation/scaling/translation on any non-z axis, you could safely code animations the 2nd way.

**Comment by mrossini-ethz** [comment]
Send me a simple example with the first one, please.

**Comment by anonimo82** [comment]
Nevermind, I've just realized Blender won't work with animations, so it's only for exporting if it would.
IMHO, I think it should be useless to export animations without having the ability to further elaborate it alone.

By the way, my first desc ribed method could be seen with FreeStyle SVG exporter, rendering animation and importing into Inkscape shows a frame set one on top of the other.

Big thanks anyhow, at least for your willing to do this.

**Comment by mrossini-ethz** [comment]
Get the latest version (devel branch). You will find an "Animate" checkbox below the SVG button. It will use the timeline (start, end) of Blender and the FPS setting in the render menu to produce the animation.

Please test it thoroughly. I expect problems with long animations (playback, not render). Also, I noted that viewing animated SVGs (in Firefox) uses a lot of CPU.

**Comment by anonimo82** [comment]
I can't try this out because of incompatibility with Blender 2.8
Look at my other issue

Il giorno dom 30 dic 2018, 18:20 Marco Rossini <notifications@github.com>
ha scritto:

**Comment by mrossini-ethz** [comment]
Then install blender 2.79. Maybe you can install both at the same time. Version 2.8 is still beta and I don't have that installed right now and therefore can't work on it. I don't have time for it either.

**Comment by anonimo82** [comment]
Ok, I'll do

Il giorno dom 30 dic 2018, 18:40 Marco Rossini <notifications@github.com>
ha scritto:

**Comment by anonimo82** [comment]
It's working as expected.
I only like to suggest, if you want, non z transformations could be coded as SVG animations (not frame flip) - look here: http://www.cheat-sheets.org/own/svg/index.xhtml

By the way, if you want, you could contribute to SVG Import script adding support for both animation styles, creating keyframes for each transform.

I know this is really big, let me know whatever you decide.

**Comment by mrossini-ethz** [comment]
What you call "non z transformations" will never happen.
The SVG import plugin is a separate issue.

I'll keep this open until bugs are fixed.

**Comment by anonimo82** [comment]
Thanks anyhow

Il giorno lun 31 dic 2018, 09:31 Marco Rossini <notifications@github.com>
ha scritto:
