### ISSUE TITLE
Render test

### ISSUE THREAD

**Issue by anonimo82** [mrossini-ethz/vector-render#6]
I'm attaching an archive containing:
 - Test .blend file
 - Regular render
 - Vector render
 - Comment .txt file

Please, see it.
[VectorTest.zip](https://github.com/mrossini-ethz/vector-render/files/3000128/VectorTest.zip)

**Comment by anonimo82** [comment]
Any help?

**Comment by mrossini-ethz** [comment]
Here is the comment from the text file:

> Hello.
> I tried to subdivide a cube multiple times and I lit it with a spot light.
> If you open the expected (render) result, you'll see there's some parts of the cube which are just partially lit.
> In the result, those faces are lit like the light hit them, but they're not, and since I subdivided the cube, I'd expect to have dark and light quads (faces).
> Please, get back.

Of course it doesn't work. If you look at the Readme for the add-on, you will note that

> Shading using lamps (currently limited to sun lamps).

It will not work with point or spot lamps, which is to be expected.

Treating any lamp as a sun lamp is actually a bug. This needs to be fixed. You will then not get any illumination from lamps unless it's a sun lamp.

**Comment by mrossini-ethz** [comment]
I just pushed a few commits onto the **devel** branch. It includes (limited) support for point and spot lamps as well as ambient light. Please try it. You should now get dark and light quads.

Note that if you subdivide the object to get color gradients you should probably just use a raster image instead of a vector image.

**Comment by anonimo82** [comment]
Yes, it's exactly what I want. Thanks a lot.
