### ISSUE TITLE
Can't install AddOn in Blender 2.83.5

### ISSUE THREAD

**Issue by chiaravalle** [mrossini-ethz/vector-render#8]
Hi there.
I get an error when enabling the AddOn in Blender 2.83.5, here's the output:
`Traceback (most recent call last):
File "/usr/share/blender/scripts/modules/addons_utils.py", line 351, in enable mod = __import__(module_name)
ModuleNotFoundError: No module named 'vector-render-blender-2'`

Please, help me out.

**Comment by mrossini-ethz** [comment]
Hi Chiara

Have you tried the blender-2.8 branch of the plugin? You can find it here: https://github.com/mrossini-ethz/vector-render/tree/blender-2.8

**Comment by chiaravalle** [comment]
Yes, I did. Here's the error screenshot: 
![Screenshot_2021-01-09_09-38-53](https://user-images.githubusercontent.com/71562926/104087249-9f6c2400-525e-11eb-927b-5746bf86678f.png)

**Comment by chiaravalle** [comment]
I guess the module name misses a ".8"

**Comment by mrossini-ethz** [comment]
Ah, yes I remember. The problem was, that the "." in the branch name caused blender to not work properly.

**Comment by chiaravalle** [comment]
Ok, thanks. How can I fix?
Will you update your repo?

**Comment by mrossini-ethz** [comment]
I created a new branch blender-2-80. Try it please.

**Comment by chiaravalle** [comment]
Now it loads, but I can't see Vector Render in Properties -> Render
Thanks a lot btw

EDIT: Nevermind, I found it

**Comment by mrossini-ethz** [comment]
Alright, have fun! I hope I will be able to find the time to continue developing the addon.

**Comment by chiaravalle** [comment]
Yes, I'd really like some readable SVG output. Maybe you can borrow ideas from Glaxnimate (https://glaxnimate.mattbas.org/) like the clear markup and animation support.
Edit: And maybe support for basic JavaScript actions like in Titania (https://github.com/create3000/titania)
